# Streamlit Secrets Template
# Copy this file to .streamlit/secrets.toml and fill in your actual credentials

[reddit]
client_id = "kA1wJ1cpmNqK2ScgSIJMUQ"
client_secret = "_RB3Gr3lmBLQysBTh16vMItCJXghJQ"
user_agent = "MindTrack:v1.0 (by /u/Adventurous-Eye-1555)"